<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Smartphone Galaxy Z Fold 5',
                'description' => 'Smartphone layar lipat tercanggih dengan performa multitasking maksimal.',
                'image' => 'Smartphone Galaxy Z Fold 5.jpg',
                'quantity' => 15,
                'price' => 24999000.00,
                'original_price' => 26999000.00,
                'weight' => 500,
                'sold_count' => 5,
                'category_id' => 1, // Elektronik
                'store_id' => 1,
            ],
            [
                'name' => 'Laptop Gaming ROG Zephyrus',
                'description' => 'Laptop gaming tipis dengan RTX 4070 dan layar 240Hz.',
                'image' => 'Laptop Gaming ROG Zephyrus.jpg',
                'quantity' => 10,
                'price' => 32500000.00,
                'original_price' => 35000000.00,
                'weight' => 2500,
                'sold_count' => 2,
                'category_id' => 1,
                'store_id' => 1,
            ],
            [
                'name' => 'Kemeja Flanel Slim Fit',
                'description' => 'Kemeja flanel bahan premium, nyaman digunakan sehari-hari.',
                'image' => 'Kemeja Flanel Slim Fit.jpg',
                'quantity' => 50,
                'price' => 199000.00,
                'original_price' => 250000.00,
                'weight' => 300,
                'sold_count' => 25,
                'category_id' => 2, // Fashion
                'store_id' => 2,
            ],
            [
                'name' => 'Sepatu Running Ultra Boost',
                'description' => 'Sepatu lari dengan bantalan empuk untuk kenyamanan maksimal.',
                'image' => 'Sepatu Running Ultra Boost.jpg',
                'quantity' => 30,
                'price' => 2100000.00,
                'original_price' => 2800000.00,
                'weight' => 800,
                'sold_count' => 12,
                'category_id' => 2,
                'store_id' => 2,
            ],
            [
                'name' => 'Kopi Arabika Gayo 250g',
                'description' => 'Biji kopi pilihan dari dataran tinggi Gayo Aceh.',
                'image' => 'Kopi Arabika Gayo 250g.jpg',
                'quantity' => 100,
                'price' => 85000.00,
                'original_price' => 95000.00,
                'weight' => 260,
                'sold_count' => 60,
                'category_id' => 3, // Food & Beverage
                'store_id' => 3,
            ],
            [
                'name' => 'Meja Kerja Minimalis',
                'description' => 'Meja kayu solid dengan desain minimalis untuk ruang kerja.',
                'image' => 'Meja Kerja Minimalis.jpg',
                'quantity' => 8,
                'price' => 1250000.00,
                'original_price' => 1500000.00,
                'weight' => 15000,
                'sold_count' => 3,
                'category_id' => 4, // Home Living
                'store_id' => 4,
            ],
            [
                'name' => 'Smart TV 4K 55 Inch',
                'description' => 'Nonton film serasa di bioskop dengan kualitas gambar 4K HDR.',
                'image' => 'Smart TV 4K 55 Inch.jpg',
                'quantity' => 12,
                'price' => 7800000.00,
                'original_price' => 8500000.00,
                'weight' => 12000,
                'sold_count' => 7,
                'category_id' => 1,
                'store_id' => 1,
            ],
            [
                'name' => 'Headset Bluetooth Noise Cancelling',
                'description' => 'Blokir suara bising dan nikmati musik dengan kualitas jernih.',
                'image' => 'Headset Bluetooth Noise Cancelling.jpg',
                'quantity' => 40,
                'price' => 3450000.00,
                'original_price' => null,
                'weight' => 400,
                'sold_count' => 15,
                'category_id' => 1,
                'store_id' => 1,
            ],
            [
                'name' => 'Tas Ransel Outdoor 40L',
                'description' => 'Tas kuat dan tahan air, cocok untuk hiking dan traveling.',
                'image' => 'Tas Ransel Outdoor 40L.jpg',
                'quantity' => 20,
                'price' => 650000.00,
                'original_price' => 800000.00,
                'weight' => 1200,
                'sold_count' => 9,
                'category_id' => 5, // Sports & Outdoor
                'store_id' => 2,
            ],
            [
                'name' => 'Jam Tangan Analog Kulit',
                'description' => 'Desain klasik dengan strap kulit asli, elegan untuk acara formal.',
                'image' => 'Jam Tangan Analog Kulit.jpg',
                'quantity' => 25,
                'price' => 1850000.00,
                'original_price' => 2200000.00,
                'weight' => 200,
                'sold_count' => 4,
                'category_id' => 2,
                'store_id' => 2,
            ],
            [
                'name' => 'Serum Vitamin C 30ml',
                'description' => 'Mencerahkan kulit dan menyamarkan noda hitam dalam 7 hari.',
                'image' => 'Serum Vitamin C 30ml.jpg',
                'quantity' => 150,
                'price' => 120000.00,
                'original_price' => 150000.00,
                'weight' => 100,
                'sold_count' => 89,
                'category_id' => 6, // Beauty
                'store_id' => 5,
            ],
            [
                'name' => 'Mouse Wireless Ergonomis',
                'description' => 'Mencegah pegal pada tangan saat bekerja lama di depan komputer.',
                'image' => 'Mouse Wireless Ergonomis.jpg',
                'quantity' => 60,
                'price' => 450000.00,
                'original_price' => 550000.00,
                'weight' => 150,
                'sold_count' => 30,
                'category_id' => 1,
                'store_id' => 1,
            ],
            [
                'name' => 'Set Pisau Dapur Steinless',
                'description' => 'Satu set pisau tajam anti karat isi 5 pcs.',
                'image' => 'Set Pisau Dapur Steinless.jpg',
                'quantity' => 35,
                'price' => 299000.00,
                'original_price' => 400000.00,
                'weight' => 1000,
                'sold_count' => 21,
                'category_id' => 4,
                'store_id' => 4,
            ],
            [
                'name' => 'Keyboard Mechanical RGB',
                'description' => 'Keyboard dengan switch biru dan lampu RGB yang bisa diatur.',
                'image' => 'Keyboard Mechanical RGB.jpg',
                'quantity' => 18,
                'price' => 850000.00,
                'original_price' => 1100000.00,
                'weight' => 1100,
                'sold_count' => 10,
                'category_id' => 1,
                'store_id' => 1,
            ],
            [
                'name' => 'Blender Portable USB',
                'description' => 'Buat jus di mana saja dengan blender praktis charge USB.',
                'image' => 'Blender Portable USB.jpg',
                'quantity' => 45,
                'price' => 175000.00,
                'original_price' => 250000.00,
                'weight' => 500,
                'sold_count' => 55,
                'category_id' => 4,
                'store_id' => 4,
            ],
            [
                'name' => 'Casing iPhone 15 Pro Max',
                'description' => 'Casing silikon premium dengan proteksi benturan maksimal.',
                'image' => 'Casing iPhone 15 Pro Max.jpg',
                'quantity' => 200,
                'price' => 150000.00,
                'original_price' => null,
                'weight' => 50,
                'sold_count' => 120,
                'category_id' => 1,
                'store_id' => 1,
            ],
            [
                'name' => 'Buku Resep Masakan Nusantara',
                'description' => 'Kumpulan resep masakan dari Sabang sampai Merauke.',
                'image' => 'Buku Resep Masakan Nusantara.jpg',
                'quantity' => 30,
                'price' => 95000.00,
                'original_price' => 120000.00,
                'weight' => 400,
                'sold_count' => 18,
                'category_id' => 7, // Books
                'store_id' => 3,
            ],
            [
                'name' => 'Matras Yoga Anti Slip',
                'description' => 'Matras empuk dan tidak licin, ideal untuk yoga dan workout.',
                'image' => 'Matras Yoga Anti Slip.jpg',
                'quantity' => 22,
                'price' => 320000.00,
                'original_price' => 450000.00,
                'weight' => 1500,
                'sold_count' => 14,
                'category_id' => 5,
                'store_id' => 2,
            ],
            [
                'name' => 'Powerbank 20000mAh PD',
                'description' => 'Pengisian daya cepat untuk semua jenis smartphone.',
                'image' => 'Powerbank 20000mAh PD.jpg',
                'quantity' => 55,
                'price' => 499000.00,
                'original_price' => 600000.00,
                'weight' => 450,
                'sold_count' => 40,
                'category_id' => 1,
                'store_id' => 1,
            ],
            [
                'name' => 'Lampu Meja LED Smart',
                'description' => 'Lampu belajar yang bisa diatur tingkat kecerahannya via aplikasi.',
                'image' => 'Lampu Meja LED Smart.jpg',
                'quantity' => 28,
                'price' => 550000.00,
                'original_price' => null,
                'weight' => 800,
                'sold_count' => 6,
                'category_id' => 4,
                'store_id' => 4,
            ],
        ];

        foreach ($products as $product) {
            Product::create([
                'name' => $product['name'],
                'slug' => Str::slug($product['name']),
                'description' => $product['description'],
                'image' => $product['image'],
                'quantity' => $product['quantity'],
                'price' => $product['price'],
                'original_price' => $product['original_price'],
                'weight' => $product['weight'],
                'sold_count' => $product['sold_count'],
                'category_id' => $product['category_id'],
                'store_id' => $product['store_id'],
            ]);
        }
    }
}